--DROP TABLE CE_CATEGORIES;     
CREATE TABLE CE_CATEGORIES
    (CATEGORY_SURR_ID NUMBER (38,0),
     CATEGORY_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR(256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR(256) NOT NULL,
     CATEGORY_NAME VARCHAR(256) NOT NULL,
     PRIMARY KEY(CATEGORY_SURR_ID),
     UPDATE_DT DATE DEFAULT sysdate NOT NULL);
     
GRANT SELECT, INSERT, UPDATE ON ce_categories TO BL_CL;