--DROP TABLE CE_COUNTRIES;     
CREATE TABLE CE_COUNTRIES
    (COUNTRY_SURR_ID NUMBER (38,0),
     COUNTRY_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR (256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR (256) NOT NULL,
     COUNTRY_CODE VARCHAR (256) NOT NULL,
     COUNTRY_NAME VARCHAR (256) NOT NULL,
     REGION_SURR_ID NUMBER (38,0) NOT NULL,
     UPDATE_DT DATE DEFAULT sysdate NOT NULL,
     PRIMARY KEY(COUNTRY_SURR_ID)
     , constraint fk_region_c FOREIGN KEY(REGION_SURR_ID) REFERENCES CE_REGIONS (REGION_SURR_ID)
);
     
GRANT SELECT, INSERT, UPDATE ON ce_countries TO BL_CL;