--DROP TABLE CE_CUSTOMERS;          
CREATE TABLE CE_CUSTOMERS
    (CUSTOMER_SURR_ID NUMBER (38,0),
     CUSTOMER_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR (256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR (256) NOT NULL,
     PERSONAL_ID VARCHAR (256) NOT NULL,
     FIRST_NAME VARCHAR (256) NOT NULL,
     LAST_NAME VARCHAR (256) NOT NULL,
     EMAIL VARCHAR (256) NOT NULL,
     ADDRESS_SURR_ID NUMBER (38,0) NOT NULL ,
     UPDATE_DT DATE DEFAULT sysdate NOT NULL,
     PRIMARY KEY(CUSTOMER_SURR_ID)
    ,constraint fk_address_c FOREIGN KEY(ADDRESS_SURR_ID) REFERENCES CE_ADDRESSES (ADDRESS_SURR_ID)
    );
    
GRANT SELECT, INSERT, UPDATE ON ce_customers TO BL_CL;