create table cities
(city_id int generated by default as identity,
city varchar (100) not null,
country varchar (100) not null,
primary key (city_id)
);

create table addresses
(address_id int generated by default as identity,
address varchar (100) not null,
city_id int,
foreign key (city_id) references cities (city_id),
primary key (address_id)
);

create table customers 
    (id int generated by default as identity,
     personal_id varchar (100) not null,
     first_name varchar (100) not null,
     last_name varchar (100) not null,
     email varchar (100) not null,
     address_id int not null, 
     phone varchar (100),
     primary key (id),
     foreign key (address_id) references addresses (address_id)
    );

create table checking_accounts
(acc_id int generated by default as identity,
id int not null,
acc_number varchar (100) not null,
account_type varchar (100) not null,
balance int,
update_dt date,
foreign key (id) references customers (id)
);

insert into  cities (city, country)
values
    ('Minsk', 'Belarus'),
    ('Mogilev', 'Belarus'),
    ('Vitebsk', 'Belarus'),
    ('Grodno', 'Belarus'),
    ('Gomel', 'Belarus'),
    ('Brest', 'Belarus');   

insert into addresses (address, city_id)
values
    ('Goretsky 1-1', 1),
    ('Snogur 2', 1),
    ('Holodnaya 5-235', 5),
    ('Vilnusskaja 78', 3),
    ('Yesraytr 8', 2),
    ('Brythew 585', 3);   

insert into  customers (personal_id, first_name, last_name, email, address_id, phone)
values
    ('VN23658745UT', 'Ivan', 'Petrov', 'dfjk@jkdsfjl', 1, '+3752869812'),
    ('VA98512657UT', 'Zoia', 'Nikonova', 'sfjlk@skflsjl', 2, '+3755214785'),
    ('VP12365478UT', 'Mia', 'Sulai', 'jhnn@jkflksjf', 3, '+3755212123'),
    ('VZ14785236UT', 'Lu', 'Nhyg', 'sf@jkflksj', 4, '+3758745693'),
    ('VA96325874UT', 'Byi', 'Tyvben', 'dfs@sfnm', 5, '+3750123654'),
    ('VY52869354UT', 'Uyt', 'Mjilo', 'vg@sfskjlkj', 6, '+3753258712');   

   
insert into  checking_accounts (id, acc_number, account_type, balance, update_dt)
values
    (1, 'BY123456789', 'deposit', 980, current_date),
    (1, 'BY123321575', 'estimated', 103, current_date),
    (2, 'BY12742589', 'deposit', 85697, current_date),
    (3, 'BY123324561', 'estimated', 7458, current_date),
    (4, 'BY124125712', 'deposit', 525, current_date),
    (5, 'BY124125712', 'deposit', 525, current_date),
    (5, 'BY124125712', 'estimated', 525, current_date);   
   
create or replace view customer_data as 
	select c.id, personal_id, first_name, last_name, email, address, city, country, phone, acc_number, account_type, balance
	from customers c
	left join addresses a on c.address_id = a.address_id
	left join cities ct on ct.city_id = a.city_id
	left join checking_accounts ca on ca.id = c.id;

create or replace procedure transfer(
   sender int,
   receiver int, 
   amount dec
)
language plpgsql    
as $$
begin
    update checking_accounts 
    set balance = balance - amount 
    where id = sender;

    -- adding the amount to the receiver's account
    update checking_accounts 
    set balance = balance + amount 
    where id = receiver;

    commit;
end;$$

call transfer (3,2,100);
select * from customer_data
order by id;