--DROP TABLE CE_PAYMENT_TYPES;
CREATE TABLE CE_PAYMENT_TYPES
    (PAYMENT_TYPE_SURR_ID NUMBER (38),
     PAYMENT_TYPE_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR (256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR (256) NOT NULL,
     PAYMENT_TYPE VARCHAR (256)  NOT NULL,
     PAYMENT_ACCOUNT VARCHAR (256) NOT NULL,
     UPDATE_DT DATE DEFAULT sysdate NOT NULL,
     PRIMARY KEY(PAYMENT_TYPE_SURR_ID));
     
GRANT SELECT, INSERT, UPDATE ON ce_payment_types TO BL_CL;