--DROP TABLE CE_CITIES;     
CREATE TABLE CE_CITIES
    (CITY_SURR_ID NUMBER (38,0),
     CITY_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR (256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR (256) NOT NULL,
     CITY VARCHAR (256) NOT NULL,
     COUNTRY_SURR_ID NUMBER (38,0) NOT NULL,
     UPDATE_DT DATE DEFAULT sysdate NOT NULL,
     PRIMARY KEY(CITY_SURR_ID)
     ,constraint fk_country_c FOREIGN KEY(COUNTRY_SURR_ID) REFERENCES CE_COUNTRIES (COUNTRY_SURR_ID)
     );

GRANT SELECT, INSERT, UPDATE ON ce_cities TO BL_CL;