--DROP TABLE CE_EMPLOYEES_SCD;     
CREATE TABLE CE_EMPLOYEES_SCD
    (EMPLOYEE_SURR_ID NUMBER (38,0),
     EMPLOYEE_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR (256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR (256) NOT NULL,
     PERSONAL_ID VARCHAR (256) NOT NULL,
     FIRST_NAME VARCHAR (256) NOT NULL,
     LAST_NAME VARCHAR (256) NOT NULL,
     EMAIL VARCHAR (256) NOT NULL,
     ADDRESS_SURR_ID NUMBER (38,0) NOT NULL,
     EMPLOYEE_TYPE VARCHAR (256) NOT NULL,
     START_DT DATE NOT NULL,
     END_DT DATE NOT NULL,
     CURRENT_FLAG VARCHAR2(256) NOT NULL,
     UPDATE_DT DATE DEFAULT sysdate NOT NULL,
     PRIMARY KEY(EMPLOYEE_SURR_ID, START_DT)
     , constraint fk_address_e FOREIGN KEY(ADDRESS_SURR_ID) REFERENCES CE_ADDRESSES (ADDRESS_SURR_ID)
     );
     
GRANT SELECT, INSERT, UPDATE ON ce_employees_scd TO BL_CL;