--DROP TABLE CE_PRODUCTS;          
CREATE TABLE CE_PRODUCTS
    (PRODUCT_SURR_ID NUMBER (38,0),
     PRODUCT_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR (256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR (256) NOT NULL,
     PRODUCT_NAME VARCHAR (256) NOT NULL,
     PRODUCT_DESC VARCHAR (256) NOT NULL,
     CATEGORY_SURR_ID NUMBER (38,0) NOT NULL,
     PRODUCT_COST NUMBER (8,2) NOT NULL,
     PRODUCT_PRICE NUMBER (8,2) NOT NULL,
     WAREHOUSE_SURR_ID NUMBER (38,0) NOT NULL,
     TOTAL_UNIT VARCHAR (256) NOT NULL,
     UPDATE_DT DATE DEFAULT sysdate NOT NULL,
     PRIMARY KEY(PRODUCT_SURR_ID)
     ,constraint fk_warehouse_p FOREIGN KEY(WAREHOUSE_SURR_ID) REFERENCES CE_WAREHOUSES(WAREHOUSE_SURR_ID)
     ,constraint fk_warehouse_c FOREIGN KEY(CATEGORY_SURR_ID) REFERENCES CE_CATEGORIES(CATEGORY_SURR_ID)
);
     
GRANT SELECT, INSERT, UPDATE ON ce_products TO BL_CL;