--DROP TABLE CE_REGIONS;   
CREATE TABLE CE_REGIONS
    (REGION_SURR_ID NUMBER (38,0),
     REGION_SRC_ID VARCHAR (256) NOT NULL,
     SOURCE_SRC_SYSTEM VARCHAR (256) NOT NULL,
     SOURCE_SRC_ENTITY VARCHAR (256) NOT NULL,
     REGION VARCHAR (256) NOT NULL,
     UPDATE_DT DATE DEFAULT sysdate NOT NULL,
     PRIMARY KEY(REGION_SURR_ID));
     
GRANT SELECT, INSERT, UPDATE ON ce_regions TO BL_CL;